// Generated by CoffeeScript 1.4.0
(function() {
  var SavingsCalculator;

  SavingsCalculator = (function() {

    function SavingsCalculator() {
      this.constants = {
        fuelDollarsSavedPerMinPerYearPerAC: 68454,
        crewDollarsSavedPerMinPerYearPerAC: 17519,
        departuresPerACPerDay: 4,
        daysPerYear: 365,
        hoursFlownPerDayPerAC: 10
      };
      this.fleetSizes = {
        small: 60,
        medium: 120,
        large: 710
      };
      this.inputs = {
        blockMinutesSaved: 2.5,
        fleetSize: this.fleetSizes['medium']
      };
      this.intermediaries = {};
      this.outputs = {};
      this.calculate();
    }

    SavingsCalculator.prototype.calculate = function() {
      this.calculateDeparturesPerYear();
      this.calculateHoursFlownPerYear();
      this.calculateFuelSavings();
      this.calculateMinutesSavedPerYear();
      this.calculateHoursSavedPerYear();
      this.calculateCrewCostSavings();
      this.calculateNumberACSaved();
      this.calculateTotalSavings();
      this.calculateDeparturesPerDay();
      console.log(this.intermediaries);
      return console.log(this.outputs);
    };

    SavingsCalculator.prototype.calculateDeparturesPerYear = function() {
      var inter;
      inter = this.intermediaries;
      return inter['departuresPerYear'] = this.inputs.fleetSize * this.constants.departuresPerACPerDay * this.constants.daysPerYear;
    };

    SavingsCalculator.prototype.calculateHoursFlownPerYear = function() {
      var inter;
      inter = this.intermediaries;
      return inter['hoursFlownPerYear'] = this.inputs.fleetSize * this.constants.hoursFlownPerDayPerAC * this.constants.daysPerYear;
    };

    SavingsCalculator.prototype.calculateFuelSavings = function() {
      var out;
      out = this.outputs;
      return out['fuelSavingsPerYear'] = this.constants.fuelDollarsSavedPerMinPerYearPerAC * this.inputs.blockMinutesSaved * this.inputs.fleetSize;
    };

    SavingsCalculator.prototype.calculateMinutesSavedPerYear = function() {
      var out;
      out = this.outputs;
      return out['minutesSavedPerYear'] = this.inputs.blockMinutesSaved * this.intermediaries.departuresPerYear;
    };

    SavingsCalculator.prototype.calculateHoursSavedPerYear = function() {
      var out;
      out = this.outputs;
      return out['hoursSavedPerYear'] = out['minutesSavedPerYear'] / 60;
    };

    SavingsCalculator.prototype.calculateCrewCostSavings = function() {
      var out;
      out = this.outputs;
      return out['crewCostSavingsPerYear'] = this.constants.crewDollarsSavedPerMinPerYearPerAC * this.inputs.blockMinutesSaved * this.inputs.fleetSize;
    };

    SavingsCalculator.prototype.calculateNumberACSaved = function() {
      var out;
      out = this.outputs;
      return out['acSavedPerYear'] = this.outputs['hoursSavedPerYear'] / (this.intermediaries['hoursFlownPerYear'] / this.inputs.fleetSize);
    };

    SavingsCalculator.prototype.calculateTotalSavings = function() {
      var out;
      out = this.outputs;
      return out['totalSavingsPerYear'] = out['fuelSavingsPerYear'] + out['crewCostSavingsPerYear'];
    };

    SavingsCalculator.prototype.calculateDeparturesPerDay = function() {
      var out;
      out = this.outputs;
      return out['departuresPerDay'] = this.inputs.fleetSize * this.constants.departuresPerACPerDay;
    };

    return SavingsCalculator;

  })();

  window.SavingsCalculator = SavingsCalculator;

}).call(this);
